### ISSUE TITLE
/sethome causes nullpointer exception in 1.16.1

### ISSUE THREAD

**Issue by shueja-personal** [NyliumMC/Essentials#17]
**Information**
- Minecraft Version: 1.16.1
- Fabric API Version: fabric-api-0.14.1+build.372-1.16
- OS: Windows client, unknown server host OS (Server.pro)
- Other installed mods: 
![FC mod list](https://user-images.githubusercontent.com/32416547/86703536-d53b0200-bfc8-11ea-91a0-fe2228e7600e.PNG)

**Describe the issue**
/sethome command results in NullPointerException

**Crash/Error logs**
If the game crashes or console errors are present, please attach the log here using a text paste service (such as gist or hastebin):
https://hastebin.com/halevijiqo.sql
**To Reproduce**
Run /sethome dragonhold (This is the name I used, but I doubt it matters)
it gives the "Unexpected error occured" and the above console message

**Expected behavior**
I was expecting it to return some feedback that wasn't an error message.

**Additional context**
If you need any just ask.

**Comment by i509VCB** [comment]
@martmists for some reason the home model handler happens to be null

```
kotlin.KotlinNullPointerException: null

at io.github.nyliummc.essentials.entities.EssentialsRegistry.getModelHandler(EssentialsRegistry.java:113) ~[essentials-base-0.2.0+1.16.1.jar:?]
```
