### ISSUE TITLE
Warps and Homes not working 1.16.1

### ISSUE THREAD

**Issue by GlowKitty** [NyliumMC/Essentials#19]
**Information**
- Minecraft Version: 1.16.1
- Fabric API Version: 0.14.1+build.372-1.16
- OS: Ubuntu Server 20.04 LTS
- Other installed mods: Lithium

I'm having issues with warps and homes, anytime I issue the commands I get "An unexpected error occurred while trying to execute that command" in the chat, and much later I get errors in my logs, attached below.

**Crash/Error logs**
log attached in txt file below
[mc2log2.txt](https://github.com/NyliumMC/Essentials/files/4891660/mc2log2.txt)

**To Reproduce**
use /setwarp <name>
use /warp list
use /warp set <name>
use /sethome
(I can't use /home or /warp as I haven't created any yet)

**Expected behavior**
creation of warps, homes, etc

**Additional context**
I am running my Minecraft instance in a docker container, but I don't know if that could be causing any issues, let me know if there is any extra context or testing I can do to help.

**Comment by i509VCB** [comment]
Direct cause looks to be the same as #17 but applies in another context.

**Comment by martmists** [comment]
Fixed in 0.2.1
