### ISSUE TITLE
/home lag/bug

### ISSUE THREAD

**Issue by skythebro** [NyliumMC/Essentials#20]
**Information**
- Minecraft Version: [1.16.1]
- Fabric API Version: [0.8.9+build.203-1.16.1]
- OS: [Windows 10]
- Other installed mods: 
![image](https://user-images.githubusercontent.com/20849134/86957581-38f53480-c15b-11ea-896f-6286981f7898.png)

**Describe the issue**
When going to home by doing /home the player will look into a random direction every time(sometimes just straight up or straight down) Also it freezes the server when any player does /home

**Crash/Error logs**
No console errors present just server lag: 
![image](https://user-images.githubusercontent.com/20849134/86957919-b15bf580-c15b-11ea-85fd-f0fb9941bf5d.png)

**To Reproduce**
1. Type in /sethome home and enter
2. Type /home home press enter
3. Result

**Expected behavior**
I expect it to take less time (no freeze) and to look in the same direction every time after teleport

**Comment by skythebro** [comment]
The lag also happens when using command /spawn

**Comment by skythebro** [comment]
I have found out that the "lag" is caused by the teleportation delay
![image](https://user-images.githubusercontent.com/20849134/86962911-ed935400-c163-11ea-8014-66a541c01bfa.png)
which for some reason makes the server lag if you put it at 0 seconds the server lag is gone

**Comment by martmists** [comment]
@i509VCB Look into how to run tasks delayed on the server without halting it, logic is in essentials-base

**Comment by i509VCB** [comment]
Mart are you blocking the server thread?

**Comment by martmists** [comment]
apparently

**Comment by sdaugherty** [comment]
I'd also suggest a message to the player when there's a teleport delay... 

"Teleporting in 3....2... 1"
