### ISSUE TITLE
/setwarp returning error

### ISSUE THREAD

**Issue by skythebro** [NyliumMC/Essentials#22]
Information

Minecraft Version: [1.16.1]
Fabric API Version: [0.8.9+build.203-1.16.1]
OS: [Windows 10]
Other installed mods:
![image](https://user-images.githubusercontent.com/20849134/86958516-963db580-c15c-11ea-8381-193acf799cca.png)

Describe the issue
If you type in /setwarp {name} this returns an error :
![image](https://user-images.githubusercontent.com/20849134/86959298-db161c00-c15d-11ea-8274-5b1cacad67f2.png)
![image](https://user-images.githubusercontent.com/20849134/86959304-df423980-c15d-11ea-9e21-600703040b98.png)

Crash/Error logs
No errors present

To Reproduce
1. Type in /setwarp {anyname}
2. Result is error message Kotlin.KotlinNullPointerException

Expected behavior
I expect it to set a warp point

**Comment by skythebro** [comment]
![image](https://user-images.githubusercontent.com/20849134/86962485-4e6e5c80-c163-11ea-8fa9-0fd6154806c3.png)

**Comment by martmists** [comment]
Should be fixed in 0.2.1

**Comment by skythebro** [comment]
but it's not though, i installed the lastest version

**Comment by i509VCB** [comment]
Is the log having the exact same issue?

**Comment by martmists** [comment]
Will be fixed in 0.2.2
