### ISSUE TITLE
Claims system

### ISSUE THREAD

**Issue by justinvvitale** [NyliumMC/Essentials#24]
**Describe what you'd like**
A new module that is aimed towards providing grief prevention. I see that there's already a SQL-based persistence system. At the current stage, I believe that you could provide a way for players to protect their property without much™ work.

Below is my rough guess on how this system will work (The simplest form):

Commands:

- /claim - will attempt to claim the chunk you're currently standing in + radius variation. If chunk is already owned, send a request to the player (Must be online, simplest form)
- /unclaim - unclaim the chunk you're standing in if you own it. + radius variation
- /chunk info - Provide information about the chunk, date it was claimed, owner, size
- /chunk preview (Optional) - Just puts bedrock on the chunk borders or something with the chunk the player is stand in + any connected chunks. (Could probably integrate this with your dynmap implementation)

When a player claims a chunk, that chunk is the key in a table. That entry will look something like:
chunkpos, dimension, players(list or something of people who have permission) + any extra information

As for enforcing the protection, that's a fairly straight forward approach for fabric (for an okayish implementation). 
Firstly a mixin to
![image](https://user-images.githubusercontent.com/4002351/87222342-478b5800-c3b6-11ea-8368-0ce560a57ee2.png)
that is used for spawn protection, could be adapted to check the database for the chunk position. This would provide basic breaking/interacting protection. Then there's additional mixins that could be done to protect against mob killing and explosions, pistons and etc. However, this isn't a necessity, if players just claim a safety boundary around their claim.

Not sure about the performance impact of this approach but shouldn't be too bad right?

**Comment by martmists** [comment]
One concern I have with this proposal is how to deal with people wanting to use a different claim system such as Towny or similar. The mixin would need to be in a common module-claims like we do with currency and teleport, but adding a specific implementation would require adding a feature in the API to disable it. Alternatively module-claims could provide the implementation and we can have a module-simpleclaims which handles chunk- based claims.
