### ISSUE TITLE
This shouldn't take long, but i didn't want to waste my time so if someone could point me in the right direction.

### ISSUE THREAD

**Issue by emerycw7** [NyliumMC/Essentials#44]
![image](https://user-images.githubusercontent.com/68492638/87868365-ea1d7b00-c962-11ea-866b-49910b67b5dc.png)

**Comment by rmortes** [comment]
I think this mod requires fabric API (https://www.curseforge.com/minecraft/mc-mods/fabric-api)

**Comment by natanfudge** [comment]
Creating empty clause???

**Comment by emerycw7** [comment]
![image](https://user-images.githubusercontent.com/68492638/87880191-a9068480-c9bd-11ea-968a-987f8ef7a609.png)

**Comment by emerycw7** [comment]
OK thank @rmortes for pointing me in the right direction, i was able to boot and I am fine now. I will close this loop after saying that in the end I got the Fabric API from @rmortes and then had to get Kotlin https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin/files/all?filter-game-version=1738749986%3A64806.
