### ISSUE TITLE
Server Crash trying to load essentials-module-datapacks

### ISSUE THREAD

**Issue by Ivan0xFF** [NyliumMC/Essentials#47]
**Information**
- Minecraft Version: 1.16.1
- Fabric API Version: 0.15.1+build.380
- OS: Docker on Ubuntu
- Other installed mods: 

**Describe the issue**
Server fails to start, crashes during load.

**Crash/Error logs**
https://gist.github.com/Ivan0xFF/b771733ab367b2b11f1b0e38bf8f9efd

**Expected behavior**
Server loads correctly

**Comment by martmists** [comment]
Fixed in 0.2.4
