### ISSUE TITLE
Server crash with essentials-module-teleport (happens with essentials-module-datapacks too) (remapping issue).

### ISSUE THREAD

**Issue by CamperSamu** [NyliumMC/Essentials#48]
**Information**
- Minecraft Version: 1.16.1 server
- Fabric API Version: 1.15.1 b380
- OS: PebbleHost server (Linux? - ???)
- Other installed mods: Full EfF package 0.2.4, ViaFabric (+ViaVer, ViaBack, ProtocolSupp), Carpet, Tree Chopper, Vanilla death chest, silk spawners, eldrich mobs, simplex, river redux, ecotones, cave biomes, mo'structures, repurposed structures, rpgstats, tinytweaks, PolyMC, OfflineSkins, CustomSkinLoader, nbtcrafting, mobs attempt parkour, photoallergic creeper, prone, TCP, lithium, phosphor, hot furnaces, compressed blocks, boatfix, armorstandutils, better signs and frames. (I may have forgot to add some mods to the list)

**Describe the issue**
Server crash with essentials-module-teleport.

**Crash/Error logs**
https://hastebin.com/agiwebobuy.sql

**To Reproduce**
Launch the server with every EfF module.

**Expected behavior**
The server should boot.

**Comment by martmists** [comment]
great, stuff isn't getting remapped again. @i509VCB pls help

**Comment by CamperSamu** [comment]
Oh great! I love when this stuff happens...
(Also I didn't realized it was a remapping issue lol, sorry for duplicating the issue)

**Comment by martmists** [comment]
Don't install essentials-api and you should be good (as stated in the readme)
