### ISSUE TITLE
ok, now the server just dies.

### ISSUE THREAD

**Issue by CamperSamu** [NyliumMC/Essentials#51]
when running a (Essentials) command or joining the server when certain modules are loaded, now it just dies and freezes.
idk.
no crash log is generated.

**Comment by CamperSamu** [comment]
sorry for harrassing with reports, but I can't figure out the issue

**Comment by martmists** [comment]
:concern:

**Comment by CamperSamu** [comment]
*reverting to 0.2.3...*
