### ISSUE TITLE
Server crash with Essentials 2.6 and client bugs

### ISSUE THREAD

**Issue by BuyMyMojo** [NyliumMC/Essentials#52]
**Information**
- Minecraft Version: 1.16.1
- Fabric API Version: 0.9.0 - build 204-1.16.1
- OS: Windows 10
- Other installed mods: [image](https://i.imgur.com/wU71iVR.png)

**Describe the issue**
1.Crashes server on latest release when player joins
2.when player joins server with latest version on client side and last version on server side then player skin fails to load, tab menu becomes empty and other players dont render

**Crash/Error logs**
[Server crash log](https://gist.github.com/BuyMyMojo/1d8350b6854be2f01ea8b6fcec7325f1)

**To Reproduce**
1. install Essentials 2.6 on client
2. install Essentials 2.5 on server
3. broken

1. install Essentials 2.6 on server
2. broken

**Expected behavior**
server will crash when Essentials 2.6 is isntalled

Client will be buggy on servers with Essentials 2.6 installed while the server has 2.5

**Comment by dandin87** [comment]
Same crash. Essentials 2.6 with all modules. When Player with or without essentials joins world the server crashes.

**Comment by martmists** [comment]
A new version of module-utilities has been uploaded to fix this.
