### ISSUE TITLE
centralinventory module

### ISSUE THREAD

**Issue by sdaugherty** [NyliumMC/Essentials#60]
**Describe what you'd like**
A module which changes how inventories (such as chests) are stored on disk, so that the inventories are stored in a single place.

This makes it easier for inventories to be edited offline than they would be while embedded in the chunk data, as well as easier to back up and restore inventories, and might open up options for logging.

I'd suggest creating one file per inventory, with a GUID, and the chunk data would instead contain references to the inventories by the GUID. 

This obviously, would break vanilla datafile compatibility on the server, so conversion processes would need to be provided to go to and from this storage method, but should be possible to do without breaking vanilla clients.

**Comment by i509VCB** [comment]
This would probably also break all modded inventories (since we do have support for modded environments).

**Comment by sdaugherty** [comment]
Yeah, it doesn't seem like an easy problem to solve, I think there's a lot to gain by this, but it's probably too difficult.

**Comment by sdaugherty** [comment]
it would make solving a lot of public server admin problems easier (for example, compact and frequent backups of the things players most care about, finding dupe stashes, etc), but it's hard to say if it's worth the development time it would take

**Comment by martmists** [comment]
Out of scope for Essentials, as we try to not modify anything vanilla, and removing essentials should not break anything.
