### ISSUE TITLE
Database crash

### ISSUE THREAD

**Issue by japietru2004** [NyliumMC/Essentials#61]
**Information**
- Minecraft Version: 1.16.1
- Fabric API Version: lastest
- OS: Linux Mint
- Other installed mods: 
- Database: mariadb mysql
![obraz](https://user-images.githubusercontent.com/51274570/88484970-eac19d00-cf72-11ea-955e-333ffefa3ae1.png)
![obraz](https://user-images.githubusercontent.com/51274570/88484977-f8772280-cf72-11ea-8453-e6c686fccac6.png)

**Describe the issue**
Server crash

**Crash/Error logs**
https://hastebin.com/esevayosub.rb
https://hastebin.com/wometiduqe.rb

db error

**Expected behavior**
Claims too work.
Too essentials don't crash game

**Comment by japietru2004** [comment]
[crash-2020-07-26_15.59.51-server.txt](https://github.com/NyliumMC/Essentials/files/4977985/crash-2020-07-26_15.59.51-server.txt)
[crash-2020-07-26_15.41.48-server.txt](https://github.com/NyliumMC/Essentials/files/4977986/crash-2020-07-26_15.41.48-server.txt)

Aditionaly text log versions.

**Comment by martmists** [comment]
First error means you didn't set up PostgreSQL correctly, the second one is a known bug in claims

**Comment by japietru2004** [comment]
You were telling to change from mysql on fabric discord

**Comment by japietru2004** [comment]
new one: from clear mysql mariadb usege
Crash on hastebin and in .txt
https://hastebin.com/vuyejuhifa.rb
[crash-2020-07-26_17.49.54-server.txt](https://github.com/NyliumMC/Essentials/files/4978074/crash-2020-07-26_17.49.54-server.txt)

Aditional:
Everything is fine until I punch block.

**Comment by martmists** [comment]
![image](https://user-images.githubusercontent.com/16361449/88485924-6115cd80-cf7a-11ea-9808-00db6f24547f.png)

**Comment by japietru2004** [comment]
mayby I should use datapack for claims
for now...

**Comment by japietru2004** [comment]
I know this isn't best place but what tutorial about fabric dev would you suggest for start of fabric dev ? I think about making own mod/plugin - for server only for plot security mayby upgrading source code to something better or making something own more flexsible like using item on 2 sides of plot and securing it
