### ISSUE TITLE
Support for new db options (h2, yaml, and mariadb)

### ISSUE THREAD

**Issue by japietru2004** [NyliumMC/Essentials#62]
Is it possible to add h2 database, or yaml or mariadb support for mod ?

**Comment by martmists** [comment]
yaml is not a database and mariadb (also known as mysql) is supported, though we're likely to reduce these options soon as many databases have their own constraints which is not easy to maintain properly across all.

**Comment by japietru2004** [comment]
yaml -> yml file databases
